version: '2'
services:

  php:
    build: .docker/php-fpm
    volumes:
      - .:/var/www

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - php
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - .:/var/www

  postgres:
    image: postgres:9.6-alpine
    ports:
      - '5432:5432'
